window.APP_CONFIG = {
  wordsUrl: "./data/words.json",
  dictionaryUrl: "./data/dictionary.json",
  dictionaryPrefixUrl: "./data/dictionary-prefix/{prefix}.json",
  dictionarySuggestUrl: "./data/dictionary-suggest/{prefix}.json",
  dictionaryDetailUrl: "./data/dictionary-detail/{prefix}.json",
  supabaseUrl: "https://ttzjzkzlxeuytbzkjshe.supabase.co",
  supabaseAnonKey: "sb_publishable_7eNwoD4bLbdd2GdRwdoD0w_iZakuBPk",
  reviewProgressTable: "review_progress",
  wordsTable: "vocabulary_words",
  dictionaryTable: "dictionary_entries",
  personalVocabularyTable: "personal_vocabulary",
  masteredThreshold: 10,
  contentCacheTtlMs: 1800000,
  localContentCacheTtlMs: 86400000,
  defaultProfileId: "",
  contentStats: {
    wordsCount: 185,
    dictionaryCount: 29204,
    wordsUpdatedAt: "2026-07-20T02:56:00.494Z",
    dictionaryUpdatedAt: "2026-07-20T01:26:34.365Z",
    wordsLatestTerm: "accumulate",
    dictionaryLatestTerm: "whistleblower",
  },
};
