window.APP_CONFIG = {
  wordsUrl: "./data/words.json",
  dictionaryUrl: "./data/dictionary.json",
  dictionaryPrefixUrl: "./data/dictionary-prefix/{prefix}.json",
  dictionarySuggestUrl: "./data/dictionary-suggest/{prefix}.json",
  dictionaryDetailUrl: "./data/dictionary-detail/{prefix}.json",
  supabaseUrl: "https://ttzjzkzlxeuytbzkjshe.supabase.co",
  supabaseAnonKey: "sb_publishable_7eNwoD4bLbdd2GdRwdoD0w_iZakuBPk",
  reviewProgressTable: "review_progress",
  wordsTable: "vocabulary_words",
  dictionaryTable: "dictionary_entries",
  masteredThreshold: 10,
  contentCacheTtlMs: 1800000,
  localContentCacheTtlMs: 86400000,
  defaultProfileId: "",
  contentStats: {
    wordsCount: 173,
    dictionaryCount: 26631,
    wordsUpdatedAt: "2026-06-06T02:08:05.031Z",
    dictionaryUpdatedAt: "2026-06-06T02:04:26.782Z",
    wordsLatestTerm: "obsess",
    dictionaryLatestTerm: "minuscule",
  },
};
